// src/app/javascript/services/tweet/react/tweet-area/TweetNew.tsx
import { Link } from "react-router-dom";
import { useEffect, useState } from 'react';
import { setIsLoading } from '@/services/ui/message';

import TweetClient from "../../TweetClient";

type Prop = {
  tweetClient : TweetClient;
};

export default function TweetNew({tweetClient}: Prop) {
  const [content, setContent] = useState('');
  const [errors, setErrors] = useState<any>({});

  useEffect(() => {
    console.log('init new');
  }, []);

  const onSubmit = async (e) => {
    e.preventDefault();

    setIsLoading(true);
    try {
      await tweetClient.tweetCtrl.sendTweet(content);

      setContent('');
      setErrors({});
    } catch (error) {
      if (error.response?.status === 422) {
        setErrors(error.response.data.errors);
      }
    }
    setIsLoading(false);
  };

  return (
    <div>
      <div>
        <Link to="/" className="app-btn-primary">
          一覧
        </Link>
      </div>

      <form onSubmit={onSubmit} className="mb-4 mt-10">
        <textarea
          rows={3}
          className="w-full border rounded p-2"
          placeholder="What's happening?"
          value={content}
          onChange={(e) => setContent(e.target.value)}
        />
        {errors.content && (
          <p className="text-red-600">{errors.content[0]}</p>
        )}
        <button type="submit" className="mt-2 app-btn-primary">
          Tweet
        </button>
      </form>
    </div>
  );
}

// src/app/javascript/services/tweet/vue/tweet-area/TweetNew.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { setIsLoading, showToast } from '@/services/ui/message';
import type TweetClient from '../../TweetClient';

type Errors = {
  content?: string[];
};

const props = defineProps<{
  tweetClient: TweetClient;
}>();

const content = ref<string>('');
const errors = ref<Errors>({});

onMounted(() => {
  console.log('init new');
});

/** 送信 */
const onSubmit = async () => {
  setIsLoading(true);

  try {
    await props.tweetClient.tweetCtrl.sendTweet(content.value);

    errors.value = {};

    showToast('ツイートしました。');

    content.value = '';
  } catch (error: any) {
    if (error.response?.status === 422) {
      errors.value = error.response.data.errors;
    }
  } finally {
    setIsLoading(false);
  }
};
</script>

<template>
  <div>
    <h3 class="app-h3">新規ツイート</h3>

    <form @submit.prevent="onSubmit" class="mb-4 mt-10" id="tweetForm">
      <textarea
        rows="3"
        class="w-full border rounded p-2"
        placeholder="What's happening?"
        name="content"
        v-model="content"
      />

      <p v-if="errors?.content" class="text-red-600">
        {{ errors.content[0] }}
      </p>

      <button type="submit" class="mt-2 app-btn-primary">確認</button>
    </form>
  </div>
</template>
