// src/app/javascript/services/tweet/vue/TweetArea.vue
<template>
  <div>
    <h2 class="app-h2">ツイート</h2>

    <TweetNew :tweetClient="tweetClient" />
    <TweetList :tweetClient="tweetClient" />
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';

import TweetNew from './tweet-area/TweetNew.vue';
import TweetList from './tweet-area/TweetList.vue';
import type TweetClient from '../TweetClient';

const props = defineProps<{
  tweetClient: TweetClient;
}>();

const tweetClient = props.tweetClient;

onMounted(() => {
  // Reactの useEffect(() => {}, [])
});
</script>

// src/app/javascript/services/tweet/react/TweetArea.tsx
import { useEffect, useState } from 'react';

import TweetNew from './tweet-area/TweetNew';
import TweetList from './tweet-area/TweetList';

import TweetClient from '../TweetClient';

type Prop = {
  tweetClient: TweetClient;
};

export default function TweetRouter({ tweetClient }: Prop) {
  useEffect(() => {}, []);

  return (
    <div>
      <h2 className="app-h2">ツイート</h2>
      <TweetNew tweetClient={tweetClient} />
      <TweetList tweetClient={tweetClient} />
    </div>
  );
}
