// src/app/javascript/services/development/react/test-area-react/FormArea.tsx
import { useState } from 'react';

type Props = {
  initialListVal: number;
  initialRadioVal: string;
  initialDateTimeVal: string;
  listVals: Record<string, string>;
  radioVals: Record<string, string>;
};

/**
 * Form動作確認
 */
export default function FormArea({
  initialListVal,
  initialRadioVal,
  initialDateTimeVal,
  listVals,
  radioVals,
}: Props) {
  const [listVal, setListVal] = useState<number | null>(initialListVal);
  const [radioVal, setRadioVal] = useState<string>(initialRadioVal);
  const [dateTimeVal, setDateTimeVal] = useState<string>(initialDateTimeVal);

  /** フォームの値の確認 */
  const confirmFormValue = () => {
    console.log('confirmFormValue', {
      listVal,
      radioVal,
      dateTimeVal,
    });
  };

  return (
    <div className="app-form">
      Form動作確認
      <div className="mt-5">
        <label htmlFor="listVal" className="app-form-label">
          リスト動作確認
        </label>
        <div className="my-2">
          <select
            id="listVal"
            value={listVal ?? ''}
            onChange={(e) =>
              setListVal(e.target.value === '' ? null : Number(e.target.value))
            }
          >
            <option value="">選択してください</option>
            {Object.entries(listVals).map(([key, value]) => (
              <option key={key} value={Number(key)}>
                {value}
              </option>
            ))}
          </select>
        </div>

        <p>
          選択中: [{String(listVal)}] {typeof listVal}
        </p>
      </div>
      <div className="mt-5">
        <label className="app-form-label">ラジオボタン動作確認</label>
        <div className="space-x-3 my-2">
          {Object.entries(radioVals).map(([key, value]) => (
            <label key={key}>
              <input
                type="radio"
                value={key}
                checked={radioVal === key}
                onChange={() => setRadioVal(key)}
              />
              &nbsp;
              {value}
            </label>
          ))}
        </div>

        <p>選択中: {radioVal}</p>
      </div>
      <div className="mt-5">
        <label htmlFor="dateTimeVal" className="app-form-label">
          日時動作確認
        </label>
        <div className="my-2">
          <input
            type="datetime-local"
            id="dateTimeVal"
            value={dateTimeVal}
            className="app-form-input"
            style={{ width: 'auto' }}
            onChange={(e) => setDateTimeVal(e.target.value)}
          />
        </div>

        <p>選択中: {dateTimeVal}</p>
      </div>
      <div className="mt-5">
        <button onClick={confirmFormValue} className="app-btn-secondary">
          確認
        </button>
      </div>
    </div>
  );
}

// src/app/javascript/services/development/vue/test-area-vue/FormArea.vue
<script setup lang="ts">
/** Form動作確認 */

import { ref } from 'vue';

interface Props {
  listVal: number;
  radioVal: string;
  dateTimeVal: string;
  listVals: Record<string, string>;
  radioVals: Record<string, string>;
}

const props = defineProps<Props>();

const listVal = ref(props.listVal);
const radioVal = ref(props.radioVal);
const dateTimeVal = ref(props.dateTimeVal);

/** フォームの値の確認 */
const confirmFormValue = () => {
  console.log('confirmFormValue', {
    listVal: listVal.value,
    radioVal: radioVal.value,
    dateTimeVal: dateTimeVal.value,
  });
};
</script>

<template>
  <div class="app-form">
    Form動作確認

    <div class="mt-5">
      <label for="listVal" class="app-form-label">リスト動作確認</label>
      <select v-model="listVal" id="listVal">
        <option :value="null" key="null">選択してください</option>
        <option
          v-for="(value, key) in listVals"
          :key="key"
          :value="Number(key)"
        >
          {{ value }}
        </option>
      </select>

      <p>選択中: [{{ listVal }}] {{ typeof listVal }}</p>
    </div>

    <div class="mt-5">
      <label class="app-form-label">ラジオボタン動作確認</label>
      <div class="space-x-3">
        <label v-for="(value, key) in radioVals" :key="key">
          <input type="radio" :value="key" v-model="radioVal" />
          <span>&nbsp;{{ value }}</span>
        </label>
      </div>

      <p>選択中: {{ radioVal }}</p>
    </div>

    <div class="mt-5">
      <label for="dateTimeVal" class="app-form-label">日時動作確認</label>
      <input type="datetime-local" v-model="dateTimeVal" id="dateTimeVal" />

      <p>選択中: {{ dateTimeVal }}</p>
    </div>

    <div class="mt-5">
      <button @click="confirmFormValue" class="app-btn-secondary">確認</button>
    </div>
  </div>
</template>
