// src/app/javascript/services/development/vue/test-area-vue/ModalArea.vue
<script setup lang="ts">
/** モーダルウィンドウ動作確認 */

import { ref } from "vue";

import Modal from "@/services/ui/vue/popup/Modal.vue";

const open = ref<boolean>(false);
const modalValue = ref<string>("");

/** モーダルウィンドウの値の確認 */
const confirmModalValue = () => {
  alert(modalValue.value);
};
</script>

<template>
  <div>
    モーダルウィンドウ動作確認

    <div class="mt-5 space-y-2">
      <div class="space-x-2">
        <button
          class="app-btn-primary"
          @click="() => {open = true}"
        >
          モーダルウィンドウ
        </button>
        <button
          @click="confirmModalValue"
          class="app-btn-secondary"
        >
          確認
        </button>
      </div>
      <div>modalValue: {{ modalValue }}</div>
    </div>
  </div>

  <Modal :isOpen="open" :onClose="() => {open = false;}"">
    <h2 className="text-xl font-bold mb-2">モーダルタイトル</h2>

    <div className="my-4">
      <textarea
        rows="3"
        cols="40"
        className="w-full border rounded p-2"
        placeholder="What's happening?"
        v-model="modalValue"
      />
    </div>

    <button
      @click="() => {open = false}"
      className="app-btn-secondary"
      type="button"
    >
      閉じる
    </button>
  </Modal>

</template>

// src/app/javascript/services/development/react/test-area-react-admin/ModalArea.tsx
import { useState } from 'react';

import ModalAdmin from '@/services/ui/react/popup/ModalAdmin';

/** モーダル動作確認 */
export default function ModalArea() {
  const [open, setOpen] = useState(false);
  const [modalValue, setModalValue] = useState('');

  /** モーダルウィンドウの値の確認 */
  const confirmModalValue = () => {
    alert(modalValue);
  };

  return (
    <>
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: '0.3rem',
        }}
      >
        <div>モーダル動作確認</div>

        <div>
          <button onClick={() => setOpen(true)}>モーダルウィンドウ</button>
          <button onClick={confirmModalValue}>確認</button>
        </div>
        <div>modalValue: {modalValue}</div>
      </div>

      <ModalAdmin isOpen={open} onClose={() => setOpen(false)}>
        <h3>モーダルタイトル</h3>

        <div>
          <textarea
            rows={3}
            cols={40}
            placeholder="What's happening?"
            value={modalValue}
            onChange={(e) => setModalValue(e.target.value)}
          />
        </div>

        <button onClick={() => setOpen(false)} style={{marginTop: "1rem"}}>閉じる</button>
      </ModalAdmin>
    </>
  );
}
